version: '3'

services:
  ergo:
    image: ergoapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["uvicorn", "main:app", "--reload", "--port=8000", "--host=0.0.0.0"]
    ports:
      - "8000:8000"
    env_file:
      - .env
